# Ubuntu Media Streaming Server - Shell Aliases & Helpers
# Add this to your ~/.bashrc by running:
#   cat scripts/bashrc >> ~/.bashrc && source ~/.bashrc

# Quick status check
alias check-status='bash ~/ubuntu-media-server/check-status.sh'

# Nginx shortcuts
alias nr='sudo nginx -s reload'
alias nginx-status='systemctl status nginx'
alias nginx-log='sudo journalctl -u nginx -f'

# MistServer shortcuts
alias mist-status='systemctl status mistserver'
alias mist-log='sudo journalctl -u mistserver -f'
alias mist-restart='sudo systemctl restart mistserver'

# Show server IP and access URLs
alias server-info='echo "IP: $(hostname -I | awk '"'"'{print $1}'"'"')" && echo "Nginx:      http://$(hostname -I | awk '"'"'{print $1}'"'"'):8080" && echo "MistServer: http://$(hostname -I | awk '"'"'{print $1}'"'"'):4242"'
